### ISSUE TITLE
Configurable "bgWidth" and "graphHeight"

### ISSUE THREAD

**Issue by arionl** [iamanai/ModernGadgets#38]
I wanted the graphs to be a bit bigger so I found that if I changed these settings in ```@Resources\Settings\Stylesheet.inc``` they worked perfectly - everything scaled as expected when I updated them. Sounds like these would be good settings to have as configurable options if possible.

**Comment by iamanai** [comment]
Since I am so OCD, I actually designed the boundaries of the skins in ModernGadgets (the length/width, the offset for the invisible border, etc.) to be fully customizable through the StyleSheet. I did consider having text boxes in the config skins, but I decided against it because most people won't want to customize them (I think so, anyway...) and I don't want to clutter the settings skins much more than they already are.

However, I will be adding a button to open the stylesheet directly from the global config skin in the next major update, so power users can go in and tweak the settings to their liking.

Thanks for the suggestion though!

**Comment by arionl** [comment]
Thanks for the update. Personally I like having bigger/longer graphs so I can see a bit more of the performance history at a glance. Attached is a screenshot of how I have my ModernGadgets set up. Appreciate your work on this skin!
![mondernwidgets](https://user-images.githubusercontent.com/1508060/27189387-34301316-51bf-11e7-9f8f-15e26cf8d953.jpg)

**Comment by iamanai** [comment]
I won't be directly adding this feature, but what I will do is make it easy to access the stylesheet, so those who want to can go edit the values manually.
